### ISSUE TITLE
Chapter 3 TF - IDF

### ISSUE THREAD

**Issue by sai-teja-ponugoti** [practical-nlp/practical-nlp#3]
I was going through your book to learn NLP. A great effort in writing such an amazing book.

I found that the example for TF-IDF is a bit unclear in the way TF scores are calculated for the toy corpus.

Ex: dog = 1/3 and bites = 1/6, I am unable to understand how this ratios are being achieved. Please include that in the example description if possible.

**Comment by suranah** [comment]
Thank you so much, @sai-teja-ponugoti!

We will make appropriate edits to the code.
