### ISSUE TITLE
Jupyter Notebook kernel died

### ISSUE THREAD

**Issue by sony-au** [practical-nlp/practical-nlp#34]
Hi,

I was wondering if anyone knows why the Jupyter Notebook kernel kept dying when I run the below code in Ubuntu:

        # model_type: word2vec, glove or fasttext
        aug = naw.WordEmbsAug(
            model_type='word2vec', model_path='GoogleNews-vectors-negative300.bin',
            action="insert")

I was wondering if it's because the GoogleNews-vectors-negative300.bin is too large that it runs out of memory? 

Thank you.

**Comment by anujgupta82** [comment]
@sony-au most probably system running out of memory
can you pls once monitor ur system memory before and after this statement?

**Comment by sony-au** [comment]
@anujgupta82 I can't do it on Jupyter Notebook as it died, but when I ran the same on Google Colab, it used 9.1Gb memory. so you may be right, it's memory issue. I tried to increase memory as per below:

https://stackoverflow.com/questions/57948003/how-to-increase-jupyter-notebook-memory-limit

but it didn't seem to work. Any suggestion how I can do it?

Thank you.
