### ISSUE TITLE
Shap Demo not working on tensorflow >= 2.0.0

### ISSUE THREAD

**Issue by sony-au** [practical-nlp/practical-nlp#37]
ISSUE: TypeError: 'NoneType' object cannot be interpreted as an integer, when running shap on LSTM model

## Location
https://github.com/practical-nlp/practical-nlp/blob/master/Ch4/10_ShapDemo.ipynb

## Current Behavior
running the code below:
shap_values = explainer.shap_values(x_val[:5])

gives you the below error:
TypeError                                 Traceback (most recent call last)

<ipython-input-18-8d9e7ac0b3e4> in <module>()
      1 # explain the first 10 predictions
      2 # explaining each prediction requires 2 * background dataset size runs
----> 3 shap_values = explainer.shap_values(x_val[:5])
      4 
      5 import numpy as np

4 frames

/usr/local/lib/python3.6/dist-packages/shap/explainers/deep/deep_tf.py in anon()
    352                     shape = list(self.model_inputs[i].shape)
    353                     shape[0] = -1
--> 354                     data = X[i].reshape(shape)
    355                     v = tf.constant(data, dtype=self.model_inputs[i].dtype)
    356                     inputs.append(v)

TypeError: 'NoneType' object cannot be interpreted as an integer

## Expected Behavior
according to your page, we should get the below output:
Downloading data from https://s3.amazonaws.com/text-datasets/imdb_word_index.json
1646592/1641221 [==============================] - 0s 0us/step

## Possible Solution
it's likely due to shap not working properly on tensorflow 2.0.0 above
but, if we use tensorflow 1.x, then we get message that keras does not work with tf 1.x

## Steps to Reproduce
Steps are the same as the provided notebook, but added the below to install tf 2.3.0
%tensorflow_version 2.x
!pip uninstall -y tensorflow
!pip install tensorflow==2.3.0

## Context (Environment)
running the notebook on colab (on Windows 10)
python 3.6.9
shap 0.35.0 (also tried the latest version)
tf 2.3.0 (also tried 2.4.0 and 1.14)

## Possible Implementation
no working solutions identified yet

## NOTE:
also in the below code, batch_size and max_features were defined, but not used (though using them doesn't make any difference)

batch_size = 64
max_features = vocab_size + 1

#Training an LSTM with embedding on the fly

print("Defining and training an LSTM model, training embedding layer on the fly")
#modified from: 
rnnmodel = Sequential()
rnnmodel.add(Embedding(MAX_NUM_WORDS, 128))
rnnmodel.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
rnnmodel.add(Dense(2, activation='sigmoid'))
rnnmodel.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
print('Training the RNN')
rnnmodel.fit(x_train, y_train,
          batch_size=32,
          epochs=2,
          validation_data=(x_val, y_val))
score, acc = rnnmodel.evaluate(test_data, test_labels,
                            batch_size=32)
print('Test accuracy with RNN:', acc)

**Comment by varunp2k** [comment]
@sony-au 
Did you try downgrading your keras version?
https://stackoverflow.com/questions/62690377/tensorflow-compatibility-with-keras
Refer this question on stackoverflow, it might help.

**Comment by sony-au** [comment]
downgrading keras to 2.3.1 works, thank u
