### ISSUE TITLE
Chapter 3 one-hot encoding

### ISSUE THREAD

**Issue by sai-teja-ponugoti** [practical-nlp/practical-nlp#4]
1) I found that a small typo in one-hot representation.

For the toy corpus D4 representation : Given in text book :D4 is represented as [ [ 0 0 1 0 0] [0 0 0 0 1 0] [0 0 0 0 0 1]].

one-hot representation for first-word "man" is only of length 5, one zero is missing in the one-hot vector.

2) In CBOW method for learning Embeddings:

one of the sentences in the text is: Given a sentence of, say, **m words**, it assigns a probability **Pr(w1, w2, ….., wn)** to the whole sentence. 

Shouldn't be the probability of words be form w1,w2,.......**,wm** instead of **wn**

3) The dimensions used for CBOW in explanation are (V,d), whereas in  CBOW figure(3.9) the dimensions used are (V,N)

**Comment by anujgupta82** [comment]
@sai-teja-ponugoti : thanks a lot for pointing these. 
I think you meant by text in the book. For that kindly use this link to submit the Errata: 
https://www.oreilly.com/catalog/errata.csp?isbn=0636920262329

For a bug in the code, please open a issue here in the Github. Thanks a lot

**Comment by sai-teja-ponugoti** [comment]
Yeah, I was pointing to the textbook.

Sure will use that provided link
