### ISSUE TITLE
[BUG] spelling_en.txt link not working

### ISSUE THREAD

**Issue by jatinpapreja** [practical-nlp/practical-nlp#43]
This template is **ONLY** to be used for reporting bugs in the code.

## Location

chapter 2 notebook 5

## Current Behavior

(https://github.com/makcedward/nlpaug/blob/master/model/spelling_en.txt) link is not working
```--2021-03-23 16:21:45--  https://github.com/makcedward/nlpaug/blob/master/model/spelling_en.txt
Resolving github.com (github.com)... 52.69.186.44
Connecting to github.com (github.com)|52.69.186.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-23 16:21:46 ERROR 404: Not Found.
```

## Steps to Reproduce

1. run the notebook

## Context (Environment)

using colab

**Comment by varunp2k** [comment]
This link has been moved to https://github.com/makcedward/nlpaug/blob/5238e0be734841b69651d2043df535d78a8cc594/nlpaug/res/word/spelling/spelling_en.txt

**Comment by kartikay-bagla** [comment]
@jatinpapreja can you update the link and test the notebook? If it works, you can add a commit in the PR which fixes this issue.
