### ISSUE TITLE
[BUG] Wikimedia link not working

### ISSUE THREAD

**Issue by KUMAR-APURVA** [practical-nlp/practical-nlp#46]
This template is **ONLY** to be used for reporting bugs in the code.

## Location

Chapter 3 Notebook 6
## Current Behavior

Link not working
https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles-multistream14.xml-p6197595p7697594.bz2
```
--2021-03-31 18:04:43--  https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles-multistream14.xml-p6197595p7697594.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.7, 2620:0:861:1:208:80:154:7
Connecting to dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.7|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-31 18:04:43 ERROR 404: Not Found.
```
## Steps to Reproduce

1.Run the notebook

## Context (Environment)

google colab

**Comment by varunp2k** [comment]
@kartikay-bagla I think wikimedia links will continue to change, one way would be to fix on a version and have a copy of that is a bucket or a drive.
