### ISSUE TITLE
Sentiment and Emotion in Text Dataset

### ISSUE THREAD

**Issue by brianalexander** [practical-nlp/practical-nlp#6]
I don't see this dataset included in the repository and it looks like Figure Eight was absorbed by Appen.

https://www.figure-eight.com/data-for-everyone/ redirects to https://appen.com/resources/datasets/

I found the dataset on Kaggle using Google's dataset search engine.  Might be worthwhile to include the dataset in the repo or update the links in the notebook.

https://www.kaggle.com/manuelbenedicto/figure-eight-labelled-textual-dataset

**Comment by brianalexander** [comment]
Hi @varunp2k,

The chapter 4 Data folder doesn't include the dataset for the Ch4 Notebook 2 02_Doc2Vec_Example.ipynb. (Can be aquired [here](https://www.kaggle.com/manuelbenedicto/figure-eight-labelled-textual-dataset) The one you linked is for Ch4 Notebook 1 01_OnePipeline_ManyClassifiers.ipynb.

Really enjoying the book!  Thanks!

**Comment by varunp2k** [comment]
Yes @brianalexander. That data is missing. Would you like to send a pr?<br>
You can make the necessary changes to the link in the notebook and add the File into the Data folder for this Chapter.

**Comment by nishkalavallabhi** [comment]
Correct link is referred in the book's references for Chapter 4. It is this: https://www.kaggle.com/c/sa-emotions

**Comment by varunp2k** [comment]
Thank you @nishkalavallabhi
