### ISSUE TITLE
practical-nlp/Ch4/04_FastText_Example.ipynb Link Formatting 

### ISSUE THREAD

**Issue by brianalexander** [practical-nlp/practical-nlp#7]
In the first cell, the link to the dbpedia has a `#` in front of the link making it not open when clicked.

original:
`[here](#https://github.com/le-scientifique/torchDatasets/raw/master/dbpedia_csv.tar.gz)`

corrected:
`[here](https://github.com/le-scientifique/torchDatasets/raw/master/dbpedia_csv.tar.gz)`

**Comment by varunp2k** [comment]
Thank you @brianalexander for bringing this to our notice. We have now fixed it.
