### ISSUE TITLE
04_FastText_Example.ipynb - code outdated

### ISSUE THREAD

**Issue by sony-au** [practical-nlp/practical-nlp#8]
Hi, supervised is no longer supported in fasttext. I used the recommended train_supervised, but was unable to get the 97% precision/recall like you said in the book. below is my code:

## Using fastText for feature extraction and training
#from fasttext import supervised 
from fasttext import train_supervised
"""fastText expects and training file (csv), a model name as input arguments.
label_prefix refers to the prefix before label string in the dataset.
default is __label__. In our dataset, it is __class__. 
There are several other parameters which can be seen in: 
https://pypi.org/project/fasttext/
"""
#%time model = supervised(train_file, 'temp', label_prefix="__class__")
%time model = train_supervised(train_file, label_prefix="__class__", lr=1.0, epoch=25, wordNgrams=2, bucket=200000, dim=50)
results = model.test(test_file)
#print(results.nexamples, results.precision, results.recall)
def print_results(N, p, r):
    print("N\t" + str(N))
    print("P@{}\t{:.3f}".format(1, p))
    print("R@{}\t{:.3f}".format(1, r))

print_results(*results)

below is the result:
CPU times: user 6min 15s, sys: 2.64 s, total: 6min 18s
Wall time: 6min 18s
N	70000
P@1	0.481
R@1	0.481

any comments would be appreciated. thanks

**Comment by varunp2k** [comment]
Hello @sony-au, this notebook was made before the supervised was deprecated.
The dataset in the Data folder isn't the one used in the notebook. You can find the dataset which was used [here](https://www.kaggle.com/lotuswhl/dbpediafromfasttext?select=train.csv). <br> 
Thank you for bringing this to our notice. We will shortly update the repo with the corrent data . <br>We apologise for the inconvenience caused.

**Comment by nishkalavallabhi** [comment]
Hi, I just followed the notebook version (with old fasttext installation), with the downloaded data from the link given there and I got the following result:
CPU times: user 58.4 s, sys: 1.45 s, total: 59.8 s
Wall time: 12.4 s
70000 0.9787285714285714 0.9787285714285714

The reason for the difference can also be related to the implementation of train_supervised vs supervised.

**Comment by varunp2k** [comment]
Thank you @nishkalavallabhi
